---
- name: Install bootstrap packages
  apt:
    name: '{{ dotfiles_bootstrap_packages }}'
    state: present
    update_cache: true
  become: true

- name: Add APT repository keys
  apt_key:
    id: '{{ item.pubkey }}'
    keyserver: keyserver.ubuntu.com
    state: present
  become: true
  loop: '{{ dotfiles_repositories }}'

- name: Add APT repositories
  apt_repository:
    filename: '{{ item.0.name }}'
    repo: '{{ item.1 }}'
  become: true
  loop: '{{ dotfiles_repositories|subelements("repository") }}'

- name: Install system packages
  apt:
    name: '{{ dotfiles_packages }}'
    state: present
    update_cache: true
  become: true

- name: Link vim version
  alternatives:
    name: vim
    path: /usr/bin/nvim
    priority: 30
