---
- name: Get tmux version
  command: tmux -V
  changed_when: false
  check_mode: false
  ignore_errors: '{{ ansible_check_mode }}'
  register: dotfiles_tmux_version

- name: Create tmux configuration file
  template:
    src: tmux.conf
    dest: '{{ ansible_facts.user_dir }}/.tmux.conf'
    owner: '{{ ansible_facts.user_uid }}'
    group: '{{ ansible_facts.user_gid }}'
    mode: 0644
  when: dotfiles_tmux_version is success

- name: Create catalog for tmux files
  file:
    path: '{{ ansible_facts.user_dir }}/.tmux'
    state: directory
    owner: '{{ ansible_facts.user_uid }}'
    group: '{{ ansible_facts.user_gid }}'
    mode: 0755

- name: Create tmux scripts
  copy:
    src: '{{ item }}'
    dest: '{{ ansible_facts.user_dir }}/.tmux/'
    owner: '{{ ansible_facts.user_uid }}'
    group: '{{ ansible_facts.user_gid }}'
    mode: 0755
  loop: '{{ query("fileglob", "files/tmux/*.sh") }}'

- name: Create tmux terminfo definition
  copy:
    src: tmux/terminfo
    dest: '{{ ansible_facts.user_dir }}/.tmux/'
    owner: '{{ ansible_facts.user_uid }}'
    group: '{{ ansible_facts.user_gid }}'
    mode: 0640

- name: Link tmux scripts to user's PATH
  file:
    src: '{{ ansible_facts.user_dir }}/.tmux/{{ item.split("/")[-1] }}'
    path: '{{ ansible_facts.user_dir }}/bin/mux-{{ item.split("/")[-1].split(".")[0] }}'
    state: link
  loop: '{{ query("fileglob", "files/tmux/*.sh") }}'
