---
- name: Setup vim configuration
  template:
    src: vimrc.j2
    dest: '{{ ansible_facts.user_dir }}/.vimrc'
    owner: '{{ ansible_facts.user_uid }}'
    group: '{{ ansible_facts.user_gid }}'
    mode: 0644

- name: Create vim catalogs
  file:
    path: '{{ item }}'
    owner: '{{ ansible_facts.user_uid }}'
    group: '{{ ansible_facts.user_gid }}'
    mode: 0755
    state: directory
  loop:
    - '{{ ansible_facts.user_dir }}/.vim'
    - '{{ ansible_facts.user_dir }}/.vim/ftplugin'
    - '{{ ansible_facts.user_dir }}/.vim/plugged'
    - '{{ ansible_facts.user_dir }}/.vim/autoload'

- name: Install vim-plug
  get_url:
    url: '{{ dotfiles_vim_plug_url }}'
    dest: '{{ ansible_facts.user_dir }}/.vim/autoload/plug.vim'
    sha256sum: '{{ dotfiles_vim_plug_sha256_checksum }}'

- name: Setup ftplugin customisations
  copy:
    src: '{{ item }}'
    dest: '{{ ansible_facts.user_dir }}/.vim/ftplugin/'
    owner: '{{ ansible_facts.user_uid }}'
    group: '{{ ansible_facts.user_gid }}'
    mode: 0644
  loop: '{{ query("fileglob", "files/ftplugin/*") }}'

- name: Install plugins
  shell: vim -c 'PlugInstall' -c 'qa'
  args:
    creates: '{{ ansible_facts.user_dir }}/.vim/plugged/vim-jakskitags'
